australian_weather_app/urls.py
from django.urls import path, include
from australian_weather_app import views

urlpatterns = [
    path(r'home/', views.home, name="home"),

    # User management
    path(r'accounts/signup/', views.SignUp.as_view(), name="signup"),
    path(r'accounts/', include('django.contrib.auth.urls')),

    # Record management
    path(r'add_observation/', views.add_observation, \
        name="add_observation"),
    path(r'list_observations/', views.list_observations, \
        name="list_observations"),
    path(r'edit_observation/<int:observation_id>/', views.edit_observation, \
        name="edit_observation"),
    path(r'delete_observation/', views.delete_observation, \
        name="delete_observation"),

    # Prediction
    path(r'predict_rainfall/', views.predict_rainfall, name="predict_rainfall")
]

miniproject_2/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path(r'admin/', admin.site.urls),
    path(r'weather/', include('australian_weather_app.urls')),
]

australian_weather_app/models.py
from django.db import models
from django.contrib.auth.models import User

locations = (('0', 'Adelaide'), ('1', 'Albury'), ('2', 'AliceSprings'), ('3', 'BadgerysCreek'), ('4', 'Ballarat'),
             ('5', 'Bendigo'), ('6', 'Brisbane'), ('7', 'Cairns'), ('8', 'Canberra'), ('9', 'Cobar'),
             ('10', 'CoffsHarbour'), ('11', 'Dartmoor'), ('12', 'Darwin'), ('13', 'GoldCoast'), ('14', 'Hobart'),
             ('15', 'Katherine'), ('16', 'Launceston'), ('17', 'Melbourne'), ('18', 'MelbourneAirport'), ('19', 'Mildura'),
             ('20', 'Moree'), ('21', 'MountGambier'), ('22', 'MountGinini'), ('23', 'Nhil'), ('24', 'NorahHead'),
             ('25', 'NorfolkIsland'), ('26', 'Nuriootpa'), ('27', 'PearceRAAF'), ('28', 'Penrith'), ('29', 'Perth'),
             ('30', 'PerthAirport'), ('31', 'Portland'), ('32', 'Richmond'), ('33', 'Sale'), ('34', 'SalmonGums'),
             ('35', 'Sydney'), ('36', 'SydneyAirport'), ('37', 'Townsville'), ('38', 'Tuggeranong'), ('39', 'Uluru'),
             ('40', 'WaggaWagga'), ('41', 'Walpole'), ('42', 'Watsonia'), ('43', 'Williamtown'), ('44', 'Witchcliffe'),
             ('45', 'Wollongong'), ('46', 'Woomera'))


winddirs = (('0', 'E'), ('1', 'ENE'), ('2' ,'ESE'), ('3', 'N'), ('4', 'NE'),
            ('5', 'NNE'), ('6', 'NNW'), ('7', 'NW'), ('8', 'S'), ('9', 'SE'),
            ('10', 'SSE'), ('11', 'SSW'), ('12', 'SW'), ('13', 'W'), ('14', 'WNW'),
            ('15', 'WSW'))

# Create your models here.

class Observation(models.Model):
    observer = models.ForeignKey(User, on_delete=models.CASCADE)
    date = models.DateField()
    location = models.CharField(max_length=40, choices=locations)
    min_temp = models.FloatField(blank=False)
    max_temp = models.FloatField(blank=False)
    rainfall = models.FloatField(blank=False)
    wind_gust_dir = models.CharField(max_length=10, blank=False, choices=winddirs)
    wind_gust_speed = models.FloatField(blank=False)
    wind_dir_9am = models.CharField(max_length=10, blank=False, choices=winddirs)
    wind_dir_3pm = models.CharField(max_length=10, blank=False, choices=winddirs)
    wind_speed_9am = models.FloatField(blank=False)
    wind_speed_3pm = models.FloatField(blank=False)
    humidity_9am = models.FloatField(blank=False)
    humidity_3pm = models.FloatField(blank=False)
    temp_9am = models.FloatField(blank=False)
    temp_3pm = models.FloatField(blank=False)
    rain_today = models.BooleanField(blank=False)

australian_weather_app/forms.py
from django.forms import ModelForm, SelectDateWidget
from django import forms
from australian_weather_app.models import Observation
import datetime


class ObservationForm(ModelForm):
    date = forms.DateField(widget=SelectDateWidget(
        years=range(1900, 2100)), initial=datetime.date.today)

    class Meta:
        model = Observation
        exclude = ['observer']

    def __init__(self, *args, **kwargs):
        super(ObservationForm, self).__init__(*args, **kwargs)
        for visible in self.visible_fields():
            visible.field.widget.attrs['class'] = 'form-control'

australian_weather_app/views.py
from django.shortcuts import render, redirect, get_list_or_404, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect, HttpResponseNotFound, HttpResponseBadRequest
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required
from django.views.decorators.csrf import ensure_csrf_cookie
from django.urls import reverse_lazy, reverse
from django.views import generic
from australian_weather_app.models import Observation
from australian_weather_app.forms import ObservationForm

from joblib import load
import pandas as pd
import datetime
import os

# User management


class SignUp(generic.CreateView):
    form_class = UserCreationForm
    success_url = reverse_lazy('login')
    template_name = 'registration/signup.html'

# Home


def home(request):
    return render(request, 'australian_weather_app/home.html')

# Observation management


@login_required(login_url=reverse_lazy('login'))
def add_observation(request):
    if request.method == 'POST':
        form = ObservationForm(request.POST)
        if form.is_valid():
            observation = form.save(commit=False)
            observation.observer = request.user
            observation.save()

            return HttpResponseRedirect(reverse('list_observations'))
    elif request.method == "GET":
        form = ObservationForm()

    context = {
        'form': form
    }
    return render(request, \
        'australian_weather_app/observations/add_observation.html', context)


@login_required(login_url=reverse_lazy('login'))
@ensure_csrf_cookie
def list_observations(request):
    observations = Observation.objects.order_by('-id')

    context = {
        'observations': observations
    }
    return render(request, \
        'australian_weather_app/observations/list_observations.html', context)


@login_required(login_url=reverse_lazy('login'))
def edit_observation(request, observation_id):
    if request.method == 'POST':
        form = ObservationForm(request.POST)
        if form.is_valid():
            observation_to_be_updated = Observation.objects.get(
                id=observation_id)
            new_observation = form.save(commit=False)

            for attr, value in new_observation.__dict__.items():
                if attr is not 'id' and attr is not 'observer_id':
                    setattr(observation_to_be_updated, attr, value)

            observation_to_be_updated.save()

            return HttpResponseRedirect('/weather/list_observations/')
    elif request.method == 'GET':
        observation = get_object_or_404(Observation, id=observation_id)

        form = ObservationForm(instance=observation)
    context = {
        'form': form
    }
    return render(request, 'australian_weather_app/observations/edit_observation.html', context)


@login_required(login_url=reverse_lazy('login'))
def delete_observation(request):
    if request.method == 'POST':
        observation_id = request.POST.get("observation_id", None)
        observation = Observation.objects.filter(id=observation_id)

        if not observation_id:
            return HttpResponseBadRequest('<h1>Bad request.</h1>')

        if observation:
            observation.delete()
            return HttpResponseRedirect(reverse('list_observations'))

        return HttpResponseNotFound('<h1>Page not found</h1>')

def get_season(d):
    if d.month >= 12 and d.month < 3:
        return 0
    elif d.month >= 3 and d.month < 6:
        return 1
    elif d.month >= 6 and d.month < 9:
        return 2
    else:
        return 3

# Prediction


@login_required(login_url=reverse_lazy('login'))
def predict_rainfall(request):
    if request.method == 'POST':
        form = ObservationForm(request.POST)
        if form.is_valid():
            observation = form.save(commit=False)
            observation.observer = request.user
            
            file_path_base = os.path.join(
                os.path.dirname(__file__), 'ml_files')
            ml_model = load(os.path.join(file_path_base, 'ml_model.joblib'))

            transformed_observation = {
                'Date': observation.date,
                'Location': observation.location,
                'MinTemp': observation.min_temp,
                'MaxTemp': observation.max_temp,
                'Rainfall': observation.rainfall,
                'WindGustDir': observation.wind_gust_dir,
                'WindGustSpeed': observation.wind_gust_speed,
                'WindDir9am': observation.wind_dir_9am,
                'WindDir3pm': observation.wind_dir_3pm,
                'WindSpeed9am': observation.wind_speed_9am,
                'WindSpeed3pm': observation.wind_speed_3pm,
                'Humidity9am': observation.humidity_9am,
                'Humidity3pm': observation.humidity_3pm,
                'Temp9am': observation.temp_9am,
                'Temp3pm': observation.temp_3pm,
                'RainToday': observation.rain_today
            }

            transformed_observation['Season'] = get_season(transformed_observation['Date'])
            df = pd.DataFrame(data=transformed_observation, index=[0])
            df['RainToday'].replace({False: 0, True: 1}, inplace=True)

            ordered_df = df[['Season', 'Location', 'WindGustDir',
                             'WindDir9am', 'WindDir3pm', 'RainToday',
                             'Humidity3pm', 'Humidity9am', 'MaxTemp',
                             'MinTemp', 'Rainfall', 'Temp3pm',
                             'Temp9am', 'WindGustSpeed', 'WindSpeed3pm',
                             'WindSpeed9am']].values

            prediction = ml_model.predict(ordered_df)

            context = {
                'observation': observation,
                'result': prediction
            }
            return render(request, "australian_weather_app/prediction/result.html", context)
    elif request.method == "GET":
        form = ObservationForm()

        context = {
            'form': form
        }
        return render(request, 'australian_weather_app/prediction/predict_rainfall.html', context)

australian_weather_app/templates/australian_weather_app/observations/add_observation.html
{% extends 'australian_weather_app/base.html' %}

{% block title %}Add observation{% endblock %}

{% block content %}
<div class="content-container">
  <h2>Record new observation</h2>

  <form method="post">
    {% csrf_token %}
    <div class="col-md-8">
      {% include 'australian_weather_app/observations/observation_fields.html'%}
      <div class="float-right">
        <button class="btn btn-success" type="submit">Save</button>
      </div>
    </div>
  </form>
</div>
{% endblock %}

australian_weather_app/templates/australian_weather_app/observations/edit_observation.html
{% extends 'australian_weather_app/base.html' %}

{% block title %}Add observation{% endblock %}

{% block content %}
<div class="content-container">
  <h2>Edit observation</h2>

  <form method="post">
    {% csrf_token %}
    <div class="col-md-8">
      {% include 'australian_weather_app/observations/observation_fields.html'%}
      <div class="float-right">
        <button class="btn btn-success" type="submit">Save</button>
      </div>
    </div>
  </form>
</div>
{% endblock %}

australian_weather_app/templates/australian_weather_app/observations/list_observations.html
{% extends 'australian_weather_app/base.html' %}

{% load staticfiles %}
{% block extra_js %}
<script src="{% static 'australian_weather_app/js/observations.js' %}"></script>
{% endblock %}

{% block title %}Manage observations{% endblock %}

{% block content %}
<div class="content-container">
    <h2>Manage observations</h2>

    <script type="text/javascript">
        delete_url = "{% url 'delete_observation' %}"
    </script>
    {% if observations %}
    <div class="observation-list">
        {% for observation in observations %}
        <div class="observation-list-item">
            {% include 'australian_weather_app/observations/observation_item.html'%}

            {% if observation.observer.id == user.id %}
            <div class="float-right">
                <a href={% url 'edit_observation' observation.id %} class='btn btn-success'>Edit</a>
                <button class='btn btn-success' onclick="remove('{{ observation.id }}', delete_url)">Remove</button>
            </div>
            {% endif %}
        </div>

        {% endfor %}

        {% else %}
        <div class="observation-list-item">
            There are no observations yet to be display.
        </div>
        {% endif %}
    </div>
</div>
{% endblock %}

australian_weather_app/templates/australian_weather_app/observations/observation_fields.html
{{ form.non_field_errors }}

<div class="form-row">
    <div class="form-group col-md-6">
        {{ form.date.errors }}
        <label for="{{ form.date.id_for_label }}">Date:</label>
        <div class="date-inputs-container">
            {{ form.date }}
        </div>
    </div>
    <div class="form-group col-md-6">
        {{ form.location.errors }}
        <label for="{{ form.location.id_for_label }}">Location:</label>
        {{ form.location }}
    </div>
</div>
<h5>Temperature</h5>
<div class="form-row">
    <div class="form-group col-md-3">
        {{ form.min_temp.errors }}
        <label for="{{ form.min_temp.id_for_label }}">Minimum temperature:</label>
        {{ form.min_temp }}
    </div>
    <div class="form-group col-md-3">
        {{ form.date.errors }}
        <label for="{{ form.max_temp.id_for_label }}">Maximum temperature:</label>
        {{ form.max_temp }}
    </div>
    <div class="form-group col-md-3">
        {{ form.date.errors }}
        <label for="{{ form.temp_9am.id_for_label }}">Temperature (9 am):</label>
        {{ form.temp_9am }}
    </div>
    <div class="form-group col-md-3">
        {{ form.date.errors }}
        <label for="{{ form.temp_3pm.id_for_label }}">Temperature (3 pm):</label>
        {{ form.temp_3pm }}
    </div>
</div>

<h5>Wind</h5>
<div class="form-row">
    <div class="form-group col-md-2">
        {{ form.wind_gust_dir.errors }}
        <label for="{{ form..id_for_label }}">Gust direction:</label>
        {{ form.wind_gust_dir }}
    </div>
    <div class="form-group col-md-2">
        {{ form.wind_gust_speed.errors }}
        <label for="{{ form..id_for_label }}">Gust speed:</label>
        {{ form.wind_gust_speed }}
    </div>
    <div class="form-group col-md-2">
        {{ form.wind_dir_9am.errors }}
        <label for="{{ form..id_for_label }}">Direction (9 am):</label>
        {{ form.wind_dir_9am }}
    </div>
    <div class="form-group col-md-2">
        {{ form.wind_speed_9am.errors }}
        <label for="{{ form..id_for_label }}">Speed (9 am):</label>
        {{ form.wind_speed_9am }}
    </div>
    <div class="form-group col-md-2">
        {{ form.wind_dir_3pm.errors }}
        <label for="{{ form..id_for_label }}">Direction (3 pm):</label>
        {{ form.wind_dir_3pm }}
    </div>
    <div class="form-group col-md-2">
        {{ form.wind_speed_3pm.errors }}
        <label for="{{ form..id_for_label }}">Speed (3 pm):</label>
        {{ form.wind_speed_3pm }}
    </div>
</div>

<h5>Humidity</h5>
<div class="form-row">
    <div class="form-group col-md-6">
        {{ form.humidity_9am.errors }}
        <label for="{{ form.humidity_9am.id_for_label }}">Humidity (9 am):</label>
        {{ form.humidity_9am }}
    </div>
    <div class="form-group col-md-6">
        {{ form.humidity_3pm.errors }}
        <label for="{{ form.humidity_3pm.id_for_label }}">Humidity (3 pm):</label>
        {{ form.humidity_3pm }}
    </div>
</div>

<h5>Rain</h5>
<div class="form-row">
    <div class="form-group col-md-3">
        {{ form.rainfall.errors }}
        <label for="{{ form.rainfall.id_for_label }}">Rainfall:</label>
        {{ form.rainfall }}
    </div>
    <div class="form-group col-md-2">
        {{ form.rain_today.errors }}
        <label for="{{ form.rain_today.id_for_label }}">Rain today:</label>
        {{ form.rain_today }}
    </div>
</div>

australian_weather_app/templates/australian_weather_app/observations/observation_item.html
<table>
    <tr>
        <th>Observer: </th>
        <td>{{ observation.observer }}</td>
    </tr>
    <tr>
        <th>Date: </th>
        <td>{{ observation.date }}</td>
    </tr>
    <tr>
        <th>Location: </th>
        <td>{{ observation.get_location_display }}</td>
    </tr>
    <tr>
        <th>Minimum temperature: </th>
        <td>{{ observation.min_temp }}</td>
    </tr>
    <tr>
        <th>Maximum temperature: </th>
        <td>{{ observation.max_temp }}</td>
    </tr>
    <tr>
        <th>Temperature (9 am): </th>
        <td>{{ observation.temp_9am }}</td>
    </tr>
    <tr>
        <th>Temperature (3 pm): </th>
        <td>{{ observation.temp_3pm }}</td>
    </tr>
    <tr>
        <th>Wind gust direction: </th>
        <td>{{ observation.get_wind_gust_dir_display }}</td>
    </tr>
    <tr>
        <th>Wind gust speed: </th>
        <td>{{ observation.wind_gust_speed }}</td>
    </tr>
    <tr>
        <th>Wind direction (9 am): </th>
        <td>{{ observation.get_wind_dir_9am_display }}</td>
    </tr>
    <tr>
        <th>Wind speed (9 am): </th>
        <td>{{ observation.wind_speed_9am }}</td>
    </tr>
    <tr>
        <th>Wind direction (3 pm): </th>
        <td>{{ observation.get_wind_dir_3pm_display }}</td>
    </tr>
    <tr>
        <th>Wind speed (3 pm): </th>
        <td>{{ observation.wind_speed_3pm }}</td>
    </tr>
    <tr>
        <th>Humidity (9 am): </th>
        <td>{{ observation.humidity_9am }}</td>
    </tr>
    <tr>
        <th>Humidity (3 pm): </th>
        <td>{{ observation.humidity_3pm }}</td>
    </tr>
    <tr>
        <th>Rainfall: </th>
        <td>{{ observation.rainfall }}</td>
    </tr>
    <tr>
        <th>Rain today: </th>
        <td>{% if observation.rain_today %}
            Yes
            {% else %}
            No
            {% endif %}
        </td>
    </tr>
</table>